
trigger:
- main

pool:
  name: auto-test-win10


variables:
  PIP_CACHE_DIR: $(Pipeline.Workspace)/.pip


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    # addToPath: true
    architecture: 'x64'

# - task: Cache@2
#   inputs:
#     key: 'python | "$(Agent.OS)" | requirements.txt'
#     restoreKeys: | 
#       python | "$(Agent.OS)"
#       python
#     path: $(PIP_CACHE_DIR)
#   displayName: Cache pip packages

- script: python -m pip install --upgrade pip setuptools wheel 
 displayName: 'Install tools'

- script: pip install -r requirements.txt
  displayName: 'Install requirements'


- task: agent-screenshot@1

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'operation_control.py'
    workingDirectory: './'